version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: evuser
      POSTGRES_PASSWORD: evpass
      POSTGRES_DB: evdb
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
  static_volume:
